# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for Rose.exe - GUI application (no console window)."""

import os
import sys
from pathlib import Path

ROOT = Path(SPECPATH).parent  # installer/ is one level below project root

a = Analysis(
    [str(ROOT / 'installer' / 'rose_gui.py')],
    pathex=[str(ROOT)],
    binaries=[],
    datas=[
        (str(ROOT / 'agent'), 'agent'),
        (str(ROOT / 'configs'), 'configs'),
        (str(ROOT / 'scripts'), 'scripts'),
        (str(ROOT / 'run.py'), '.'),
        (str(ROOT / 'requirements-runtime.txt'), '.'),
        (str(ROOT / 'requirements-dev.txt'), '.'),
        (str(ROOT / 'pyproject.toml'), '.'),
        (str(ROOT / 'README.md'), '.'),
        (str(ROOT / 'LICENSE'), '.'),
        (str(ROOT / '.env.example'), '.'),
    ],
    hiddenimports=[
        'agent.core.agent',
        'agent.core.config',
        'agent.core.health',
        'agent.core.error_recovery',
        'agent.core.model_health',
        'agent.core.performance',
        'agent.core.resources',
        'agent.core.session_persistence',
        'agent.core.system_prompt',
        'agent.llm.base',
        'agent.llm.local_provider',
        'agent.llm.model_optimizer',
        'agent.media.vision_pipeline',
        'agent.media.vision_decision',
        'agent.media.multimodal_pipeline',
        'agent.media.ocr',
        'agent.media.grounding',
        'agent.media.screen_understanding',
        'agent.media.real_vision',
        'agent.media.storage',
        'agent.media.router',
        'agent.media.tools',
        'agent.media.analyzer',
        'agent.media.base',
        'agent.media.image_gen',
        'agent.media.video_gen',
        'agent.media.vision_tool',
        'agent.media.grounding_tool',
        'agent.media.oav_tool',
        'agent.media.observe_act_verify',
        'agent.media.multimodal',
        'agent.media.permissions',
        'agent.tools.router',
        'agent.tools.registry',
        'agent.tools.base',
        'agent.tools.permissions',
        'agent.tools.audit',
        'agent.tools.app_launcher',
        'agent.tools.cli_automation',
        'agent.tools.cli_tool',
        'agent.tools.file_automation',
        'agent.tools.filesystem_tool',
        'agent.tools.python_sandbox',
        'agent.memory.base',
        'agent.memory.context',
        'agent.memory.conversation',
        'agent.memory.long_term',
        'agent.memory.session',
        'agent.memory.summarizer',
        'agent.orchestration.autonomous',
        'agent.orchestration.autonomous_loop',
        'agent.orchestration.planner',
        'agent.orchestration.executor',
        'agent.orchestration.verifier',
        'agent.orchestration.observer',
        'agent.orchestration.recovery',
        'agent.orchestration.events',
        'agent.orchestration.limits',
        'agent.orchestration.models',
        'agent.orchestration.tool_scorer',
        'agent.orchestration.tool_selector',
        'agent.orchestration.tool_catalog',
        'agent.orchestration.state',
        'agent.orchestration.task_state',
        'agent.orchestration.persistence',
        'agent.orchestration.memory_integration',
        'agent.orchestration.capability_analyzer',
        'agent.orchestration.enhanced_planner',
        'agent.orchestration.validator',
        'agent.browser.manager',
        'agent.browser.tools',
        'agent.browser.session',
        'agent.browser.policy',
        'agent.browser.permissions',
        'agent.browser.models',
        'agent.os_control.keyboard',
        'agent.os_control.mouse',
        'agent.os_control.screen',
        'agent.os_control.windows',
        'agent.os_control.system',
        'agent.os_control.permissions',
        'agent.web.server',
        'agent.web.events',
        'agent.web.application',
        'agent.startup',
        'llama_cpp',
        'numpy',
        'PIL',
        'cv2',
        'pytesseract',
        'rich',
        'pydantic',
        'dotenv',
        'yaml',
        'tqdm',
        'diskcache',
        'jinja2',
        'huggingface_hub',
        'requests',
        'pyautogui',
        'pygetwindow',
        'mouseinfo',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter.test',
        'unittest',
        'email',
        'html',
        'http',
        'xml',
        'pydoc',
        'doctest',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Rose',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,  # No console window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='file_version_info.txt' if os.path.exists('file_version_info.txt') else None,
    uac_admin=False,  # App doesn't need admin, only installer does
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Rose',
)
